//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankingDocentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AprobacionDocente
    {
        public int nIdAprobacionDocente { get; set; }
        public int nIdDocenteSugerido { get; set; }
        public int Usuario_nIdUsuario { get; set; }
        public string cEstado { get; set; }
    
        public virtual DocenteSugerido DocenteSugerido { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
