//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankingDocentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleDocente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleDocente()
        {
            this.RankingDocente = new HashSet<RankingDocente>();
        }
    
        public int idDetalleDocente { get; set; }
        public int Carrera_nIdCarrera { get; set; }
        public int Curso_nIdCurso { get; set; }
        public int Docente_nIdDocente { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Docente Docente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RankingDocente> RankingDocente { get; set; }
    }
}
