//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankingDocentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocenteSugerido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocenteSugerido()
        {
            this.AprobacionDocente = new HashSet<AprobacionDocente>();
        }
    
        public int nIdDocenteSugerido { get; set; }
        public string cNombres { get; set; }
        public string cApePaterno { get; set; }
        public string cApeMaterno { get; set; }
        public int Carrera_nIdCarrera { get; set; }
        public int Curso_nIdCurso { get; set; }
        public int Usuario_nIdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AprobacionDocente> AprobacionDocente { get; set; }
        public virtual Carrera Carrera { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
