//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankingDocentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingDocente
    {
        public int idRankingDocente { get; set; }
        public string cComentarios { get; set; }
        public Nullable<int> nPuntucionCriterio1 { get; set; }
        public Nullable<int> nPuntucionCriterio2 { get; set; }
        public Nullable<int> nPuntucionCriterio3 { get; set; }
        public Nullable<System.DateTime> dtFecha { get; set; }
        public int nIdUsuario { get; set; }
        public int nIdDetalleDocente { get; set; }
        public Nullable<int> nPuntuacionPromedio { get; set; }
    
        public virtual DetalleDocente DetalleDocente { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
