//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankingDocentes.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.AprobacionDocente = new HashSet<AprobacionDocente>();
            this.DocenteSugerido = new HashSet<DocenteSugerido>();
            this.RankingDocente = new HashSet<RankingDocente>();
        }
    
        public int nIdUsuario { get; set; }
        public string cContrasena { get; set; }
        public string cNombres { get; set; }
        public string cApePaterno { get; set; }
        public string cApeMaterno { get; set; }
        public string cCorreo { get; set; }
        public string cEstado { get; set; }
        public int nIdTipoUsuario { get; set; }
        public int nIdCarrera { get; set; }

        [NotMapped]
        public int cConfirmarContraseña { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AprobacionDocente> AprobacionDocente { get; set; }
        public virtual Carrera Carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocenteSugerido> DocenteSugerido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RankingDocente> RankingDocente { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
